"""baseline: current legacy schema (users, grants, notifications, stats)

Revision ID: 9ffc96b8fba3
Revises:
Create Date: 2026-09-08 12:50:34.157792

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ffc96b8fba3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=1000), nullable=True),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("detected_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grants_detected_at"), "grants", ["detected_at"], unique=False
    )
    op.create_table(
        "stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total_scrapes", sa.Integer(), nullable=True),
        sa.Column("total_notifications", sa.Integer(), nullable=True),
        sa.Column("total_users", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("last_scrape_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_subscribed", sa.Boolean(), nullable=True),
        sa.Column("total_scrapes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_chat_id"), "users", ["chat_id"], unique=True)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("grant_id", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "grant_id", name="uq_notification_user_grant"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Baseline'ın geri alınması desteklenmez.

    ADR-004'e göre yıkıcı downgrade'ler güvenli kabul edilmez: bu revizyonu
    geri almak, production'daki users/grants/notifications/stats tablolarını
    ve tüm verilerini silmek anlamına gelir. İhtiyaç halinde restore
    yedekten yapılmalıdır, otomatik DROP ile değil.
    """
    raise RuntimeError(
        "Baseline downgrade desteklenmiyor; ADR-004 geregi yikici degildir. "
        "Geri alma gerekiyorsa backup/restore prosedurunu kullanin."
    )
